routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main.index');
})->name('home');

Route::get('/email', function () {
    return view('email.subscription');
});


Route::group([
    'namespace' => 'Main',
    'as' => 'main.',
], function ($route) {
    $route->name('subscribe.register')->post('/subscribe-register', 'MainController@subscribe');
    $route->name('about.print')->get('/about-me-print', function() {
        return view('main.about-me-print-v2');
    });

    $route->name('product.list')->get('/product', 'ProductController@index');
    $route->name('product.detail')->get('/product/{product}', 'ProductController@detail');

    $route->name('post.list')->get('/blog', 'PostController@index');
    $route->name('post.tag')->get('/blog/category/{tag}', 'PostController@tag');
    $route->name('post.detail')->get('/blog/{post}', 'PostController@detail');
    $route->name('feed')->get('/feed', 'MainController@feed');
});

Route::group([
    'namespace' => 'Admin',
    'prefix' => 'ura',
    'as' => 'admin.',
    'middleware' => ['auth']
], function ($route) {
    $route->name('post')->get('/post', 'PostController@index');
    $route->name('post.create')->get('/post/create', 'PostController@create');
    $route->name('post.store')->post('/post/create', 'PostController@store');
    $route->name('post.show')->get('/post/{post}', 'PostController@show');
    $route->name('post.edit')->get('/post/{post}/edit', 'PostController@edit');
    $route->name('post.update')->post('/post/{post}/edit', 'PostController@store');
    $route->name('post.image-upload')->post('/image-upload/', 'PostController@image_upload');

    $route->name('tag')->get('/tag', 'TagController@index');
    $route->name('subscription')->get('/subscription', 'SubscriptionController@index');

    $route->name('product')->get('/product', 'ProductController@index');
    $route->name('product.create')->get('/product/create', 'ProductController@create');
    $route->name('product.store')->post('/product/create', 'ProductController@store');
    $route->name('product.show')->get('/product/{product}', 'ProductController@show');
    $route->name('product.edit')->get('/product/{product}/edit', 'ProductController@edit');
    $route->name('product.update')->post('/product/{product}/edit', 'ProductController@store');
    $route->name('product.images')->get('/product/{product}/image-upload/', 'ProductController@img_show');
    $route->name('product.image-upload')->post('/product/{product}/image-upload/', 'ProductController@image_upload');

});
// Auth::routes();

Route::get('/ura/login', [
    'as' => 'login',
    'uses' => 'Auth\LoginController@showLoginForm'
  ]);
Route::post('/ura/login', [
'as' => '',
'uses' => 'Auth\LoginController@login'
]);
Route::post('/ura/logout', [
'as' => 'logout',
'uses' => 'Auth\LoginController@logout'
]);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Post extends Model
{
    const DRAFT = 0;
    const PUBLISH = 1;
    const UNPUBLISHED = 2;

    protected $fillable = [
        'title',
        'body',
        'overview',
        'banner',
        'thumbnail',
        'keywords',
        'status',
        'slug',
        'tags'
    ];
    protected $casts = [
        'tags' => 'array'
    ];

    public function getJoinedTagAttribute() {
        if (count($this->tags) == 0)
            return '';
        return implode(', ', $this->tags);
    }

    public function getRouteKeyName() {
        return 'slug';
    }

    public function getPublishDateAttribute() {
        return Carbon::parse($this->created_at)->toFormattedDateString();
    }

    public function getThumbnailAttribute($value) {
        return $value ?: '';
    }

    public function getBannerAttribute($value) {
        return $value ?: '';
    }

    public function suggestions() {
        $return = Post::orderBy('updated_at')->where('id','!=', $this->id);
        $tags = $this->tags;
        $return = $return->where(function($query) use ($tags) {
            foreach($this->tags as $tag) {
                $query = $query->orWhereJsonContains('tags', $tag);
            }
        });

        return $return;
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Post;
use Carbon\Carbon;
use Illuminate\Support\Str;

class PostController extends Controller
{
    public function index(Request $request) {
        $search = $request->get('search');
        $posts = Post::orderBy('updated_at', 'desc');
        if ($search != '') {
            $posts = $posts->where('title', 'like', '%'.$search.'%');
        }
        $posts = $posts->paginate(20);
        return view('admin.post.index', compact('posts', 'search'));
    }

    public function create() {
        return view('admin.post.update');
    }

    public function show(Post $post) {
        return view('main.post.detail', compact('post'));
    }

    public function store(Request $request, Post $post) {
        $request->validate([
            'title' => 'required',
            'body' => 'required'
        ]);
        
        if (is_null($post)) {
            $post = new Post();
        }

        $tags = collect();
        foreach(explode(',', $request->get('tags')) as $tag) {
            if ($tag != '')
                $tags->push(trim($tag));
        }
        $post->fill([
            'title' => $request->get('title'),
            'body' => $request->get('body'),
            'status' => $request->get('status'),
            'overview' => $request->get('overview'),
            'keywords' => $request->get('keywords'),
            'tags' => $tags->unique()->values()
        ]);
        $slug = '';
        if (is_null($post->created_at)) {
            $datenow = Carbon::now()->timestamp;
            $slug = (Str::slug($request->get('title')) ?: $request->get('title')).'-'.$datenow;
            $post->slug = $slug;
        } else {
            $slug = $post->slug;
        }

        if ($request->hasFile('banner')) {
            $post->banner = $this->upload($request->file('banner'), $slug.'-banner');
        }
        if ($request->hasFile('thumbnail')) {
            $post->thumbnail = $this->upload($request->file('thumbnail'), $slug.'-thumbnail');
        }

        $post->save();
        return redirect()->route('admin.post.show', compact('post'))->with('success', 'New post saved.');
    }

    public function edit(Post $post) {
        return view('admin.post.update', compact('post'));
    }

    public function image_upload(Request $request) {
        $datenow = Carbon::now();
        $file=$request->file('file');
        $path= '/assets/images/upload';
        $filename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);
        $newFileName = $filename.'-'.$datenow->timestamp.'.'.$extension;
        $imgpath = $file->move(public_path($path), $newFileName);
        return response()->json([
            'location' => URL($path.'/'.$newFileName)
        ]);
    }

    public function upload($file, $name = '') {
        if (empty($file))
            return '';
        
        $path= '/assets/images/upload';
        $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);
        $timestamp = Carbon::now()->timestamp;
        $name = $name.'-'.$timestamp.'.'.$extension;
        $imgpath = $file->move(public_path($path), $name);
        return $path.'/'.$name;
    }
    
}

app/Http/Controllers/Main/PostController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Post;
use App\Models\Tag;

class PostController extends Controller
{
    public function index(Request $request) {
        $search = $request->get('search');
        $posts = Post::orderBy('updated_at', 'desc');
        if ($search != '') {
            $posts = $posts->where('name', 'like', '%'.$search.'%');
        }
        $posts = $posts->where('status', Post::PUBLISH)->paginate(10);
        return view('main.post.list', compact('posts', 'search'));
    }

    public function detail(Post $post) {
        return view('main.post.detail', compact('post'));
    }

    public function tag(Request $request, Tag $tag) {
        $search = $request->get('search');
        $posts = $tag->posts();
        if ($search != '') {
            $posts = $posts->where('name', 'like', '%'.$search.'%');
        }
        $posts = $posts->where('status', Post::PUBLISH)->paginate(20);
        return view('main.post.list', compact('posts', 'search'));
    }
}

resources/views/admin/post/index.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="mb-3">
                <span>Post</span>
                <div class="float-right">
                    <a class="btn btn-primary" href="{{ route('admin.post.create') }}">New Post</a>
                </div>
            </h2>
            <div class="mb-3">
                <form method="GET" class="form-inline">
                    <div class="form-row">
                        <div class="col">
                            <input type="text" name="search" class="form-control" value="{{ $search }}" />
                        </div>
                        <div class="col">
                            <button class="btn btn-outline-dark" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            @include('include.alert')
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive-sm">
                        <table id="data" class="table small text-nowrap table-hover table-dropdown-hover">
                            <thead>
                                <tr>
                                    <th class="py-2">Title</th>
                                </tr>
                            </thead>
                            <tbody>
                        @foreach ($posts as $item)
                                <tr>
                                    <td><a href="{{ route('admin.post.show', $item) }}">{{ $item->title }}</a></td>
                                </tr>
                        @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="d-flex">
            {{ $posts->appends($_GET)->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/post/update.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="mb-3">
                <span>Post</span>
            </h2>
            <div>
            @include('include.alert')
            <form role="form" method="POST" action="{{ isset($post) ? route('admin.post.update', $post) : route('admin.post.store') }}" novalidate class="form-button-disabled" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group row">
                    <label for="title" class="col-sm-3 col-form-label border-right">Title</label>
                    <div class="col-sm-9">
                        <input id="title" type="text" class="form-control" name="title" value="{{ isset($post) ? $post->title : old('title') }}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label border-right">Overview</label>
                    <div class="col-sm-9">
                        <textarea style="min-height: 200px;" type="text" class="form-control" name="overview">{{ isset($post) ? $post->overview : old('overview') }}</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="tinycontent" class="col-sm-3 col-form-label border-right">Body</label>
                    <div class="col-sm-9">
                        <textarea id="tinycontent" style="min-height: 200px;" type="text" class="form-control" name="body">{{ isset($post) ? $post->body : old('body') }}</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="title" class="col-sm-3 col-form-label border-right">Tags</label>
                    <div class="col-sm-9">
                        <input id="tags" type="text" class="form-control" name="tags" value="{{ isset($post) ? $post->joined_tag : old('tags') }}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="title" class="col-sm-3 col-form-label border-right">Keywords</label>
                    <div class="col-sm-9">
                        <input id="keywords" type="text" class="form-control" name="keywords" value="{{ isset($post) ? $post->keywords : old('keywords') }}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label border-right">Thumbnail</label>
                    <div class="col-sm-9">
                        <div class="custom-file mb-3">
                            <input type="file" class="custom-file-input" id="thumbnail" name="thumbnail" onchange="document.getElementById('imgThumbnail').src = window.URL.createObjectURL(this.files[0])" />
                            <label class="custom-file-label" for="customFile">{{ isset($post) ? $post->thumbnail : 'Choose File' }}</label>
                        </div>
                        <img id="imgThumbnail" src="{{ isset($post) && $post->thumbnail != '' ?  URL($post->thumbnail) : 'https://dummyimage.com/100x100/d1d1d1/dbdbdb.png' }}" alt="image" title="image" width="100px" />
                        <div class="py-1">
                            <button type="button" class="btn btn-sm btn-secondary" onclick="document.getElementById('thumbnail').value = '';document.getElementById('imgThumbnail').src = 'https://dummyimage.com/100x100/d1d1d1/dbdbdb.png';">Remove</button>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label border-right">Banner</label>
                    <div class="col-sm-9">
                        <div class="custom-file mb-3">
                            <input type="file" class="custom-file-input" id="banner" name="banner" onchange="document.getElementById('imgBanner').src = window.URL.createObjectURL(this.files[0])" />
                            <label class="custom-file-label" for="customFile">{{ isset($post) ? $post->banner : 'Choose File' }}</label>
                        </div>
                        <img id="imgBanner" src="{{ isset($post) && $post->banner != '' ?  URL($post->banner) : 'https://dummyimage.com/100x100/d1d1d1/dbdbdb.png' }}" alt="image" title="image" width="100px" /><br />
                        <div class="py-1">
                            <button type="button" class="btn btn-sm btn-secondary" onclick="document.getElementById('banner').value = '';document.getElementById('imgBanner').src = 'https://dummyimage.com/100x100/d1d1d1/dbdbdb.png';">Remove</button>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="status" class="col-sm-3 col-form-label border-right">Status</label>
                    <div class="col-sm-9">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="status" id="cbx_draft" value="0" {{ isset($post) && $post->status == '0' || old('status') == '0' || !isset($post) ? 'checked' : '' }}>
                            <label class="form-check-label" for="cbx_draft">Draft</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="status" id="cbx_publish" value="1" {{ isset($post) && $post->status == '1' || old('status') == '1' ? 'checked' : '' }}>
                            <label class="form-check-label" for="cbx_publish">Publish</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="status" id="cbx_unpublish" value="2" {{ isset($post) && $post->status == '2' || old('status') == '2' ? 'checked' : '' }}>
                            <label class="form-check-label" for="cbx_unpublish">Unpublish</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-9 offset-sm-3">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script src="https://cdn.tiny.cloud/1/5c7f4h2e4xyigs7jqeb41nz2ku0empfoyw9r4o9gqbjf83tf/tinymce/5/tinymce.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
<script type="text/javascript">
    $(function() {
        bsCustomFileInput.init()
    });

    tinymce.init({
        selector: 'textarea#tinycontent',
        plugins: [
                "advlist autolink lists link image charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste"
        ],
        toolbar: 'undo redo | styleselect | bold italic | link | alignleft aligncenter alignright | link image',
        min_height: 500,
        images_upload_handler: function (blobInfo, success, failure) {
           var xhr, formData;
           xhr = new XMLHttpRequest();
           xhr.withCredentials = false;
           xhr.open('POST', "{{ route('admin.post.image-upload') }}");
           var token = '{{ csrf_token() }}';
           xhr.setRequestHeader("X-CSRF-Token", token);
           xhr.onload = function() {
               var json;
               if (xhr.status != 200) {
                   failure('HTTP Error: ' + xhr.status);
                   return;
               }
               json = JSON.parse(xhr.responseText);

               if (!json || typeof json.location != 'string') {
                   failure('Invalid JSON: ' + xhr.responseText);
                   return;
               }
               success(json.location);
               console.log(json.location);
           };
           formData = new FormData();
           formData.append('file', blobInfo.blob(), blobInfo.filename());
           xhr.send(formData);
       }
    });
</script>
@stop