routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main.index');
})->name('home');

Route::get('/email', function () {
    return view('email.subscription');
});


Route::group([
    'namespace' => 'Main',
    'as' => 'main.',
], function ($route) {
    $route->name('subscribe.register')->post('/subscribe-register', 'MainController@subscribe');
    $route->name('about.print')->get('/about-me-print', function() {
        return view('main.about-me-print-v2');
    });

    $route->name('product.list')->get('/product', 'ProductController@index');
    $route->name('product.detail')->get('/product/{product}', 'ProductController@detail');

    $route->name('post.list')->get('/blog', 'PostController@index');
    $route->name('post.tag')->get('/blog/category/{tag}', 'PostController@tag');
    $route->name('post.detail')->get('/blog/{post}', 'PostController@detail');
    $route->name('feed')->get('/feed', 'MainController@feed');
});

Route::group([
    'namespace' => 'Admin',
    'prefix' => 'ura',
    'as' => 'admin.',
    'middleware' => ['auth']
], function ($route) {
    $route->name('post')->get('/post', 'PostController@index');
    $route->name('post.create')->get('/post/create', 'PostController@create');
    $route->name('post.store')->post('/post/create', 'PostController@store');
    $route->name('post.show')->get('/post/{post}', 'PostController@show');
    $route->name('post.edit')->get('/post/{post}/edit', 'PostController@edit');
    $route->name('post.update')->post('/post/{post}/edit', 'PostController@store');
    $route->name('post.image-upload')->post('/image-upload/', 'PostController@image_upload');

    $route->name('tag')->get('/tag', 'TagController@index');
    $route->name('subscription')->get('/subscription', 'SubscriptionController@index');

    $route->name('product')->get('/product', 'ProductController@index');
    $route->name('product.create')->get('/product/create', 'ProductController@create');
    $route->name('product.store')->post('/product/create', 'ProductController@store');
    $route->name('product.show')->get('/product/{product}', 'ProductController@show');
    $route->name('product.edit')->get('/product/{product}/edit', 'ProductController@edit');
    $route->name('product.update')->post('/product/{product}/edit', 'ProductController@store');
    $route->name('product.images')->get('/product/{product}/image-upload/', 'ProductController@img_show');
    $route->name('product.image-upload')->post('/product/{product}/image-upload/', 'ProductController@image_upload');

});
// Auth::routes();

Route::get('/ura/login', [
    'as' => 'login',
    'uses' => 'Auth\LoginController@showLoginForm'
  ]);
Route::post('/ura/login', [
'as' => '',
'uses' => 'Auth\LoginController@login'
]);
Route::post('/ura/logout', [
'as' => 'logout',
'uses' => 'Auth\LoginController@logout'
]);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'category',
        'name',
        'slug',
        'description',
        'content',
        'price',
        'discount',
        'status',
        'tags',
        'images',
    ];

    protected $casts = [
        'tags' => 'array',
        'images' => 'array'
    ];

    public function getJoinedTagAttribute() {
        if (count($this->tags) == 0)
            return '';
        return implode(', ', $this->tags);
    }

    public function getRouteKeyName() {
        return 'slug';
    }

    public function getImagesAttribute($value) {
        if($value) {
            return json_decode($value);
        }
        return [];
    }

    public function getThumbnailAttribute() {
        if(count($this->images) > 0)
            return collect($this->images)->first();
        return '';
    }

    public function getFinalPriceAttribute() {
        return '$ '.($this->price - $this->discount);
    }
    
    public function recommendations() {
        return Product::orderBy('updated_at')->where('status', 'active')->where('id','!=', $this->id)->where('category', $this->category);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');
        $products = Product::orderBy('updated_at', 'desc');
        if ($search != '') {
            $products = $products->where('name', 'like', '%'.$search.'%');
        }
        $products = $products->paginate(20);
        return view('admin.product.index', compact('products', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.product.update');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Product $product)
    {
        $request->validate([
            'category' => 'required',
            'product_name' => 'required',
        ]);
        
        if (is_null($product)) {
            $product = new Product();
        }

        $tags = collect();
        foreach(explode(',', $request->get('tags')) as $tag) {
            if ($tag != '')
                $tags->push(trim($tag));
        }
        
        $product->fill([
            'category' => $request->get('category'),
            'name' => $request->get('product_name'),
            'slug' => Str::slug($request->get('product_name')),
            'description' => $request->get('description'),
            'content' => $request->get('content'),
            'price' => $request->get('price') ?: 0,
            'discount' => $request->get('discount') ?: 0,
            'status' => $request->get('status'),
            'tags' => $tags->unique()->values()
        ]);

        $product->save();
        return redirect()->route('admin.product')->with('success', 'New product saved.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('admin.product.detail', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('admin.product.update', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }

    public function img_show(Product $product) {
        return view('admin.product.image-upload', compact('product'));
    }

    public function image_upload(Request $request, Product $product) {
        $datenow = Carbon::now();
        $data = collect();
        $path= '/assets/images/product';
        $slug = Str::slug($product->name);
        foreach($request->file('product_img') as $key => $file) {
            $filename = $slug;
            $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);
            $newFileName = $filename.'-'.$datenow->timestamp.'-'.$key.'.'.$extension;
            $imgpath = $file->move(public_path($path), $newFileName);
            $data->push($path.'/'.$newFileName);
        }
        $product->images = $data;
        $product->save();

        return redirect(route('admin.product.show', $product))->with('success', 'Product Updated.');
    }
}

app/Http/Controllers/Main/ProductController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;

class ProductController extends Controller
{
    public function index(Request $request) {
        $search = $request->get('search');
        $products = Product::orderBy('updated_at', 'desc');
        if ($search != '') {
            $products = $products->where('name', 'like', '%'.$search.'%');
        }
        $products = $products->where('status', 'active')->paginate(20);
        return view('main.product.list', compact('products', 'search'));
    }

    public function detail(Product $product) {
        return view('main.product.detail', compact('product'));
    }
}

resources/views/admin/product/detail.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="mb-3">
                <span>Product Detail</span>
                <div class="float-right">
                    <a class="btn btn-primary" href="{{ route('admin.product.edit', $product) }}">Edit</a>
                </div>
            </h2>
            @include('include.alert')
            <table class="table small text-nowrap table-hover table-dropdown-hover">
                <tr>
                    <td>Name</td>
                    <td>{{ $product->name }}</td>
                </tr>
                <tr>
                    <td>Category</td>
                    <td>{{ $product->category }}</td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td>{{ $product->description }}</td>
                </tr>
                <tr>
                    <td>Price</td>
                    <td>{{ $product->price }}</td>
                </tr>
                <tr>
                    <td>Discount</td>
                    <td>{{ $product->discount }}</td>
                </tr>
                <tr>
                    <td>Status</td>
                    <td>{{ $product->status }}</td>
                </tr>
                <tr>
                    <td>Thumbnails</td>
                    <td>
                        @foreach($product->images as $image)
                        <div class="mb-1">
                            <img src="{{ $image }}" alt="{{ $product->name }}" title="{{ $product->name}}" style="width: 100px;" />
                        </div>
                        @endforeach
                        <a class="btn btn-secondary" href="{{ route('admin.product.images', $product) }}">Update</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/admin/product/image-upload.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="mb-3">
                <span>Product Image</span>
            </h2>
            <form id="uploadForm" enctype="multipart/form-data" action="{{ route('admin.product.image-upload', $product) }}" method="post">
                {{ csrf_field() }}
                <div id="append">
                    <div class="py-1">
                        <input type="file" name="product_img[]" />
                    </div>
                </div>
                <div class="mb-3">
                    <button class="btn btn-secondary btn-sm" onClick="addFile()" type="button">Add</button>
                </div>
                <div class="input-group">
                    <button class="btn btn-primary" type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    function addFile() {
        $('#append').append('<div class="py-1"><input type="file" name="product_img[]" /></div>');
    }
</script>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="mb-3">
                <span>Product</span>
                <div class="float-right">
                    <a class="btn btn-primary" href="{{ route('admin.product.create') }}">New Product</a>
                </div>
            </h2>
            <div class="mb-3">
                <form method="GET" class="form-inline">
                    <div class="form-row">
                        <div class="col">
                            <input type="text" name="search" class="form-control" value="{{ $search }}" />
                        </div>
                        <div class="col">
                            <button class="btn btn-outline-dark" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            @include('include.alert')
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive-sm">
                        <table id="data" class="table small text-nowrap table-hover table-dropdown-hover">
                            <thead>
                                <tr>
                                    <th class="py-2">Name</th>
                                    <th class="py-2">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                        @foreach ($products as $item)
                                <tr>
                                    <td><a href="{{ route('admin.product.show', $item) }}">{{ $item->name }}</a></td>
                                    <td>{{ $item->status }}</td>
                                </tr>
                        @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="d-flex">
            {{ $products->appends($_GET)->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/product/update.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="mb-3">
                <span>Product</span>
            </h2>
            <div>
            @include('include.alert')
            <form role="form" method="POST" action="{{ isset($product) ? route('admin.product.update', $product) : route('admin.product.store') }}" novalidate class="form-button-disabled">
                {{ csrf_field() }}
                <div class="form-group row">
                    <label for="product_name" class="col-sm-3 col-form-label border-right">Name</label>
                    <div class="col-sm-9">
                        <input id="product_name" type="text" class="form-control" name="product_name" value="{{ isset($product) ? $product->name : old('name') }}" required />
                    </div>
                </div>
                <div class="form-group row">
                    <label for="category" class="col-sm-3 col-form-label border-right">Category</label>
                    <div class="col-sm-9">
                        <input id="category" type="text" class="form-control" name="category" value="{{ isset($product) ? $product->category : old('category') }}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="description" class="col-sm-3 col-form-label border-right">Description</label>
                    <div class="col-sm-9">
                        <textarea id="description" style="min-height: 200px;" type="text" class="form-control" name="description">{{ isset($product) ? $product->description : old('description') }}</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="tinycontent" class="col-sm-3 col-form-label border-right">Content</label>
                    <div class="col-sm-9">
                        <textarea id="tinycontent" style="min-height: 200px;" type="text" class="form-control" name="content">{{ isset($product) ? $product->content : old('content') }}</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="price" class="col-sm-3 col-form-label border-right">Price</label>
                    <div class="col-sm-9">
                        <input id="price" type="number" class="form-control" name="price" value="{{ isset($product) ? $product->price : old('price') }}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="discount" class="col-sm-3 col-form-label border-right">Discount</label>
                    <div class="col-sm-9">
                        <input id="discount" type="number" class="form-control" name="discount" value="{{ isset($product) ? $product->discount : old('discount') }}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="title" class="col-sm-3 col-form-label border-right">Tags</label>
                    <div class="col-sm-9">
                        <input id="tags" type="text" class="form-control" name="tags" value="{{ isset($product) ? $product->joined_tag : old('tags') }}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="status" class="col-sm-3 col-form-label border-right">Status</label>
                    <div class="col-sm-9">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="status" id="inlineCheckboxInactive" value="inactive" {{ isset($product) && $product->status == 'inactive' || old('status') == 'inactive' || !isset($product) ? 'checked' : '' }}>
                            <label class="form-check-label" for="inlineCheckboxInactive">Inactive</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="status" id="inlineCheckboxActive" value="active" {{ isset($product) && $product->status == 'active' || old('status') == 'active' ? 'checked' : '' }}>
                            <label class="form-check-label" for="inlineCheckboxActive">Active</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-9 offset-sm-3">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script src="https://cdn.tiny.cloud/1/5c7f4h2e4xyigs7jqeb41nz2ku0empfoyw9r4o9gqbjf83tf/tinymce/5/tinymce.min.js"></script>
<script type="text/javascript">
    $(function() {
        bsCustomFileInput.init()
    });

    tinymce.init({
        selector: 'textarea#tinycontent',
        plugins: [
                "advlist autolink lists link image charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste"
        ],
        toolbar: 'undo redo | styleselect | bold italic | link | alignleft aligncenter alignright | link image',
        min_height: 500,
        images_upload_handler: function (blobInfo, success, failure) {
           var xhr, formData;
           xhr = new XMLHttpRequest();
           xhr.withCredentials = false;
           xhr.open('POST', "{{ route('admin.post.image-upload') }}");
           var token = '{{ csrf_token() }}';
           xhr.setRequestHeader("X-CSRF-Token", token);
           xhr.onload = function() {
               var json;
               if (xhr.status != 200) {
                   failure('HTTP Error: ' + xhr.status);
                   return;
               }
               json = JSON.parse(xhr.responseText);

               if (!json || typeof json.location != 'string') {
                   failure('Invalid JSON: ' + xhr.responseText);
                   return;
               }
               success(json.location);
               console.log(json.location);
           };
           formData = new FormData();
           formData.append('file', blobInfo.blob(), blobInfo.filename());
           xhr.send(formData);
       }
    });
</script>
@stop