routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main.index');
})->name('home');

Route::get('/email', function () {
    return view('email.subscription');
});


Route::group([
    'namespace' => 'Main',
    'as' => 'main.',
], function ($route) {
    $route->name('subscribe.register')->post('/subscribe-register', 'MainController@subscribe');
    $route->name('about.print')->get('/about-me-print', function() {
        return view('main.about-me-print-v2');
    });

    $route->name('product.list')->get('/product', 'ProductController@index');
    $route->name('product.detail')->get('/product/{product}', 'ProductController@detail');

    $route->name('post.list')->get('/blog', 'PostController@index');
    $route->name('post.tag')->get('/blog/category/{tag}', 'PostController@tag');
    $route->name('post.detail')->get('/blog/{post}', 'PostController@detail');
    $route->name('feed')->get('/feed', 'MainController@feed');
});

Route::group([
    'namespace' => 'Admin',
    'prefix' => 'ura',
    'as' => 'admin.',
    'middleware' => ['auth']
], function ($route) {
    $route->name('post')->get('/post', 'PostController@index');
    $route->name('post.create')->get('/post/create', 'PostController@create');
    $route->name('post.store')->post('/post/create', 'PostController@store');
    $route->name('post.show')->get('/post/{post}', 'PostController@show');
    $route->name('post.edit')->get('/post/{post}/edit', 'PostController@edit');
    $route->name('post.update')->post('/post/{post}/edit', 'PostController@store');
    $route->name('post.image-upload')->post('/image-upload/', 'PostController@image_upload');

    $route->name('tag')->get('/tag', 'TagController@index');
    $route->name('subscription')->get('/subscription', 'SubscriptionController@index');

    $route->name('product')->get('/product', 'ProductController@index');
    $route->name('product.create')->get('/product/create', 'ProductController@create');
    $route->name('product.store')->post('/product/create', 'ProductController@store');
    $route->name('product.show')->get('/product/{product}', 'ProductController@show');
    $route->name('product.edit')->get('/product/{product}/edit', 'ProductController@edit');
    $route->name('product.update')->post('/product/{product}/edit', 'ProductController@store');
    $route->name('product.images')->get('/product/{product}/image-upload/', 'ProductController@img_show');
    $route->name('product.image-upload')->post('/product/{product}/image-upload/', 'ProductController@image_upload');

});
// Auth::routes();

Route::get('/ura/login', [
    'as' => 'login',
    'uses' => 'Auth\LoginController@showLoginForm'
  ]);
Route::post('/ura/login', [
'as' => '',
'uses' => 'Auth\LoginController@login'
]);
Route::post('/ura/logout', [
'as' => 'logout',
'uses' => 'Auth\LoginController@logout'
]);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Post extends Model
{
    const DRAFT = 0;
    const PUBLISH = 1;
    const UNPUBLISHED = 2;

    protected $fillable = [
        'title',
        'body',
        'overview',
        'banner',
        'thumbnail',
        'keywords',
        'status',
        'slug',
        'tags'
    ];
    protected $casts = [
        'tags' => 'array'
    ];

    public function getJoinedTagAttribute() {
        if (count($this->tags) == 0)
            return '';
        return implode(', ', $this->tags);
    }

    public function getRouteKeyName() {
        return 'slug';
    }

    public function getPublishDateAttribute() {
        return Carbon::parse($this->created_at)->toFormattedDateString();
    }

    public function getThumbnailAttribute($value) {
        return $value ?: '';
    }

    public function getBannerAttribute($value) {
        return $value ?: '';
    }

    public function suggestions() {
        $return = Post::orderBy('updated_at')->where('id','!=', $this->id);
        $tags = $this->tags;
        $return = $return->where(function($query) use ($tags) {
            foreach($this->tags as $tag) {
                $query = $query->orWhereJsonContains('tags', $tag);
            }
        });

        return $return;
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Post;
use Carbon\Carbon;
use Illuminate\Support\Str;

class PostController extends Controller
{
    public function index(Request $request) {
        $search = $request->get('search');
        $posts = Post::orderBy('updated_at', 'desc');
        if ($search != '') {
            $posts = $posts->where('title', 'like', '%'.$search.'%');
        }
        $posts = $posts->paginate(20);
        return view('admin.post.index', compact('posts', 'search'));
    }

    public function create() {
        return view('admin.post.update');
    }

    public function show(Post $post) {
        return view('main.post.detail', compact('post'));
    }

    public function store(Request $request, Post $post) {
        $request->validate([
            'title' => 'required',
            'body' => 'required'
        ]);
        
        if (is_null($post)) {
            $post = new Post();
        }

        $tags = collect();
        foreach(explode(',', $request->get('tags')) as $tag) {
            if ($tag != '')
                $tags->push(trim($tag));
        }
        $post->fill([
            'title' => $request->get('title'),
            'body' => $request->get('body'),
            'status' => $request->get('status'),
            'overview' => $request->get('overview'),
            'keywords' => $request->get('keywords'),
            'tags' => $tags->unique()->values()
        ]);
        $slug = '';
        if (is_null($post->created_at)) {
            $datenow = Carbon::now()->timestamp;
            $slug = (Str::slug($request->get('title')) ?: $request->get('title')).'-'.$datenow;
            $post->slug = $slug;
        } else {
            $slug = $post->slug;
        }

        if ($request->hasFile('banner')) {
            $post->banner = $this->upload($request->file('banner'), $slug.'-banner');
        }
        if ($request->hasFile('thumbnail')) {
            $post->thumbnail = $this->upload($request->file('thumbnail'), $slug.'-thumbnail');
        }

        $post->save();
        return redirect()->route('admin.post.show', compact('post'))->with('success', 'New post saved.');
    }

    public function edit(Post $post) {
        return view('admin.post.update', compact('post'));
    }

    public function image_upload(Request $request) {
        $datenow = Carbon::now();
        $file=$request->file('file');
        $path= '/assets/images/upload';
        $filename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);
        $newFileName = $filename.'-'.$datenow->timestamp.'.'.$extension;
        $imgpath = $file->move(public_path($path), $newFileName);
        return response()->json([
            'location' => URL($path.'/'.$newFileName)
        ]);
    }

    public function upload($file, $name = '') {
        if (empty($file))
            return '';
        
        $path= '/assets/images/upload';
        $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);
        $timestamp = Carbon::now()->timestamp;
        $name = $name.'-'.$timestamp.'.'.$extension;
        $imgpath = $file->move(public_path($path), $name);
        return $path.'/'.$name;
    }
    
}

app/Http/Controllers/Main/MainController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Subscription;
use App\Models\Post;
use Validator;

class MainController extends Controller
{
    public function index() {

    }

    public function subscribe(Request $request) {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required|email'
        ]);

        if ($validator->fails()) {
            $errors = collect();
            foreach($validator->errors()->all() as $error) {
                $errors->push($error);
            }
            return response()->json([
                'status' => 401,
                'message' => $validator->errors()->first()
            ]);
        }

        $subscription = Subscription::where('email', $request->get('email'))->first();
        if (!is_null($subscription) && $subscription->status) {
            return response()->json([
                'status' => 401,
                'message' => 'Email is exist.',
            ]);
        }

        if (is_null($subscription)) {
            $subscription = new Subscription();
            $subscription->fill([
                'name' => $request->get('name'),
                'email' => $request->get('email')
            ]);
        } else {
            $subscription->status = 1;
        }

        $subscription->save();

        return response()->json([
            'status' => 200,
            'message' => 'Added to subscriber list.',
        ]);
    }

    public function feed() {
        // create new feed
        $feed = \App::make('feed');

        // multiple feeds are supported
        // if you are using caching you should set different cache keys for your feeds

        // cache the feed for 60 minutes (second parameter is optional)
        $feed->setCache(60, 'laravelFeedKey');

        // check if there is cached feed and build new only if is not
        if (!$feed->isCached()) {
            $posts = Post::where('status', Post::PUBLISH)->orderBy('updated_at')->get();

            $feed->title = 'Live in Japan';
            $feed->description = 'All about my activities in Japan.';
            $feed->logo = 'http://yoursite.tld/logo.jpg';
            $feed->link = url('feed');
            $feed->setDateFormat('datetime');
            $feed->pubdate = $posts[0]->updated_at;
            $feed->lang = 'en';
            $feed->setShortening(true);
            $feed->setTextLimit(100);

            foreach ($posts as $post) {
                $feed->add($post->title, 'Emmanuel Sitinjak', url($post->slug), $post->publish_date, $post->overview, $post->body);
            }

        }

        // first param is the feed format
        // optional: second param is cache duration (value of 0 turns off caching)
        // optional: you can set custom cache key with 3rd param as string
        return $feed->render('atom');

        // to return your feed as a string set second param to -1
        // $xml = $feed->render('atom', -1);

    }
}

app/Http/Controllers/Main/PostController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Post;
use App\Models\Tag;

class PostController extends Controller
{
    public function index(Request $request) {
        $search = $request->get('search');
        $posts = Post::orderBy('updated_at', 'desc');
        if ($search != '') {
            $posts = $posts->where('name', 'like', '%'.$search.'%');
        }
        $posts = $posts->where('status', Post::PUBLISH)->paginate(10);
        return view('main.post.list', compact('posts', 'search'));
    }

    public function detail(Post $post) {
        return view('main.post.detail', compact('post'));
    }

    public function tag(Request $request, Tag $tag) {
        $search = $request->get('search');
        $posts = $tag->posts();
        if ($search != '') {
            $posts = $posts->where('name', 'like', '%'.$search.'%');
        }
        $posts = $posts->where('status', Post::PUBLISH)->paginate(20);
        return view('main.post.list', compact('posts', 'search'));
    }
}

app/Http/Controllers/Main/ProductController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;

class ProductController extends Controller
{
    public function index(Request $request) {
        $search = $request->get('search');
        $products = Product::orderBy('updated_at', 'desc');
        if ($search != '') {
            $products = $products->where('name', 'like', '%'.$search.'%');
        }
        $products = $products->where('status', 'active')->paginate(20);
        return view('main.product.list', compact('products', 'search'));
    }

    public function detail(Product $product) {
        return view('main.product.detail', compact('product'));
    }
}

resources/views/main/post/detail.blade.php
@extends('layouts.main')
@section('title', $post->title)
@section('meta_image', URL($post->banner?: $post->thumbnail))
@section('meta_description', $post->overview)
@section('meta_keywords', $post->keywords)

@section('content')
@if($post->banner)
<div class="paralax-banner" style="background-image: url('{{ $post->banner }}');"></div>
@endif
<div class="container my-5">
    <div class="row">
        <div class="col-12">
            <div class="blog-header">
                <h1 class="mb-3">{{ $post->title }}</h1>
                <div class="row text-muted small">
                    <div class="col-6">{{ $post->publish_date }}</div>
                    <div class="col-6 text-right">
                        @foreach($post->tags as $tag)
                        <a href="{{ route('main.post.tag', $tag) }}" class="text-secondary text-decoration-none">{{ $tag }}</a>
                        @if (!$loop->last)
                        &middot;
                        @endif
                        @endforeach
                    </div>
                    <div class="col-12 py-2"><div class="addthis_inline_share_toolbox"></div></div>
                </div>
                @if(Auth::check())
                <div class="py-3">
                    <a href="{{ route('admin.post.edit', $post) }}">Edit</a>
                </div>
                @endif
            </div>
            <div class="py-3 blog-post">
                {!! $post->body !!}
            </div>
        </div>
        <div class="col-12 py-2 text-center">
            <small>Share this:</small>
            <div class="addthis_inline_share_toolbox"></div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12">
        <h4 class="border-bottom pb-2 mb-3">More from me</h4>
        </div>
        @foreach($post->suggestions()->take(2)->get() as $key => $suggestion)
        <div class="col-md-6 col-12">
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="col-lg-4 col-md-4 col-12" style="min-height: 150px;">
                        <a href="{{ route('main.post.detail', $suggestion) }}" class="d-block w-100 h-100 blog-thumbnail" style="background: url('{{ $suggestion->thumbnail }}');">&nbsp;</a>
                    </div>
                    <div class="col-lg-8 col-md-8 col-12">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{{ route('main.post.detail', $suggestion) }}" class="text-secondary text-decoration-none">{{ $suggestion->title }}</a></h5>
                            <p class="card-text">
                                <small class="text-muted">{{ $suggestion->publish_date }}</small>
                                <br />
                                <small class="text-muted">
                                    @foreach($suggestion->tags as $tag)
                                    <a href="{{ route('main.post.tag', $tag) }}" class="text-secondary text-decoration-none">{{ $tag }}</a>
                                    @if (!$loop->last)
                                    &middot;
                                    @endif
                                    @endforeach
                                </small>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection

resources/views/main/post/list.blade.php
@extends('layouts.main')
@section('content')
<div class="mb-5" style="background: url('/assets/images/main/product-photo-banner.JPG') no-repeat 100%; background-attachment: fixed; background-position: top center;">
    <div class="container" style="min-height: 300px; padding-top: 100px;">
        <div class="row">
            <div class="col-12">
                <h1 class="text-white display-2">Blog</h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        @foreach($posts as $key => $post)
        <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-12">
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="col-lg-3 col-md-4 col-12" style="min-height: 150px;">
                        <a href="{{ route('main.post.detail', $post) }}" class="d-block w-100 h-100 blog-thumbnail" style="background: url('{{ $post->thumbnail }}');">&nbsp;</a>
                    </div>
                    <div class="col-lg-9 col-md-8 col-12">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{{ route('main.post.detail', $post) }}" class="text-secondary text-decoration-none">{{ $post->title }}</a></h5>
                            <p class="card-text">{{ $post->overview }}</p>
                            <p class="card-text">
                                <small class="text-muted">{{ $post->publish_date }}</small>
                                <br />
                                <small class="text-muted">
                                    @foreach($post->tags as $tag)
                                    <a href="{{ route('main.post.tag', $tag) }}" class="text-secondary text-decoration-none">{{ $tag }}</a>
                                    @if (!$loop->last)
                                    &middot;
                                    @endif
                                    @endforeach
                                </small>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
        <div class="col-12 py-3">
        {{ $posts->appends($_GET)->links() }}
        </div>
    </div>
</div>
@endsection